const bingoConfig = {
    title: "Happy Birthday, Amira!",
    options: [
        { name: "That's Not My Name", description: "The Ting Tings" },
        { name: "Cruel Summer", description: "Taylor Swift" },
        { name: "Raspberry Beret", description: "Prince" },
        { name: "All Night Long (All Night)", description: "Lionel Ritchie" },
        { name: "a thousand years", description: "Christina Perri" },
        { name: "Madre Tierra (Oye)", description: "Chayanne" },
        { name: "Call Me Maybe", description: "Carly Rae Jepsen" },
        { name: "Shake It Off", description: "Taylor Swift" },
        { name: "Hey Ya!", description: "Outkast" },
        { name: "You Make My Dreams (Come True)", description: "Daryl Hall & John Oates" },
        { name: "Shut Up and Dance", description: "WALK THE MOON" },
        { name: "Firework", description: "Katy Perry" },
        { name: "Titanium", description: "David Guetta, Sia" },
        { name: "Dynamite", description: "BTS" },
        { name: "Birthday - Remastered 2009", description: "The Beatles" },
        { name: "Butter", description: "BTS" },
        { name: "Timber", description: "Pitbull, Kesha" },
        { name: "Disparate Youth", description: "Santigold" },
        { name: "We Will Rock You", description: "Queen" },
        { name: "My Shot", description: "Lin-Manuel Miranda" },
        { name: "La Skalera", description: "Pocacama" },
        { name: "Todos los días sale el sol", description: "Bongo Botrako" },
        { name: "Ain't Got No / I Got Life", description: "Nina Simone" },
        { name: "Quiero un camión", description: "Loquillo Y Los Trogloditas" },
        { name: "House of Memories", description: "Panic! At The Disco" },
        { name: "Waka Waka (This Time for Africa)", description: "Shakira" },
        { name: "STAY", description: "The Kid LAROI, Justin Bieber" },
        { name: "Crush", description: "Tessa Violet" },
        { name: "Sugar", description: "Maroon 5" },
        { name: "Honeypie - Speed", description: "Ren" },
        { name: "Magnetic", description: "ILLIT" },
        { name: "Starfish And Coffee", description: "Prince" },
        { name: "Soy Yo", description: "Bomba Estéreo" },
        { name: "Celebrate (From \"Penguins of Madagascar\")", description: "Pitbull" },
        { name: "Dance Monkey", description: "Tones And I" },
        { name: "Can't Hold Us", description: "Macklemore, Ryan Lewis, Ray Dalton" },
        { name: "Believer", description: "Imagine Dragons" }

    ],
    eventsCount: 0,
    events: ["Cake cutting", "Opening presents", "Singing 'Happy Birthday'", "Gift bags for guests", "Group photo"],
};
